modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
issueTrackerURL="https://github.com/Electrolyte220/MysticalAgricultureTieredCrystals/"
[[mods]]
modId="matc"
version="${file.jarVersion}"
displayName="Mystical Agriculture Tiered Crystals"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture-tiered-crystals"
credits="BlakeBr0 for making Mystical Agriculture"
authors="Electrolyte"
description="Adds Tiered Crystals to Mystical Agriculture"
[[dependencies.matc]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.matc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.matc]]
    modId="cucumber"
    mandatory=true
    versionRange="[6.2.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.matc]]
    modId="mysticalagriculture"
    mandatory=true
    versionRange="[6.2.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.matc]]
    modId="mysticalagradditions"
    mandatory=false
    versionRange="[6.2.0,)"
    ordering="AFTER"
    side="BOTH"
